language: go
go:
  - 1.14.x
install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

services: mongodb

before_script:
  - sleep 3

script:
  - env GO111MODULE=on go test -coverprofile=coverage.out ./...
  - env GO111MODULE=on $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

env:
  global:
    - secure: IC5WhBu5MSR+MnV5pIc+zrSxM8qPBBfK5mmbCsAoXwwDrqr6b0Vek9d4fpowxE1fpOYXxrCl8FCdiqjI73FDsp7CUw3i5XUxTmltfNS/HZoIr1jdZyxUoBS4pO8qh+DSUKzowbE00xh2KI4C8dNq5I2MzS9TN4urokBIGPe0vX/n1Ej1hTj5mehh0RX/ewKkxwEXvhLWs5ZmgH+/H9HXaWecBqjnigJB8pEGeykDaQjN5ae2Czu/YzbPaDL8gsgNkafAWQ1BAfENypdWokGGT5ohxLbuEQDqrsB3keqQBI6pM8XJ+p46pGDfaqyoydK5vMDUdhzwJdlUqa9kGXfrQMubUWgcNtuMO6p1MQ0aRocfcHeEKAK1Qew1OX99jIZdkJcfYhsLSlc1w2MEk/PFh1YTKpMaH4vfXozIEmsKM5W1py8l3fp0kv3OMYmy4DSkzH7TG6UZ9Zl3G0qUxuNdm0uSAsyuxaiUIfldHrFAzo9a8bZeyiCVAbI0pl+pxx59FlTw/CbYfc8k75m/7Ed9yMGV8N4bYTLZglD/IRhiaQqhkfeLGx/szzIY73lrirW3pTQedAE2bx7QI+8Rehug6mIWaLYhTOBIqxejPAdWvxEvweTztxGRa9fCFj9ig3jLaf50Z8Hf9Zyv3y2PJQeQz89/M4TuXRPXBIcSaXskmPE=
    - secure: RUc9p+rUTNqsFp/9h0OxmzH2lPm1VY0kWKgq/WYEes4Pq9iXfHZ1mFy7fTLXywEDkyMFoG3QAM7KhuJ21gPH1A0lC08ZbTXVYi2Q/IzqvvM1QX422N6IyB0ezKGuXYJ+/99BZv+X8EIV5vl8DYvzX0JZeMJW31GSqdsCaNV+NMd/lMFIcrxVCoXiWluALRnRyUCt/RFDUVVQ62ZhwUxSHVoGmCC1VLlXixdwIaOuqmDla5l2o8xEQmO74KUrAo2fRF5qB4M2bycS5INWt4cRj5gg8NHOBAt/uXIb/TW9UY0owzSpVvKMD4rrYQo31xSfZ8I1HqXfvF7qzSPYpfl8tUZQNU3mbBd0/ehNk5fQ189yeqDueFLMqLdBCscW3VEJ4KCYKMwcqW3Pfbz7B3I6uUcAZZv8TEYIO68gmwRjLD/rY9KVseqgktWvfawQbIeS4xCHTaleAEC06VoFSd4lKtsLS4xPNz9Fzlq4Cm6MtrIA1e26MZMJDnMkKAaFBAZzEMfcKAGdbAlFKmm2Z8novwfENSeg3Xo9UaZpQnC4gjZfeG72t0pJ9b5mD44oiNgU3aNkZXK0RC9IB7ROzXKT2WlhTuDmBXzbEttFvT73S+I58J/FXN4ypDKutfDEuns3ZFeF81ZCjZUGmc62yBaUNudCirLA1n7qHPZIbW1IPw8=
    - secure: cQEZrcojt9O3IdIbaVT6TVgRRF/W/62sxFWO9DiXuIA7OWLJLz+BWrH/RwrreIRsFc5MoUjLtdGQPjlMEWBLkzSZAz+O6l2DST9SDikSSuFm5P/BBXfire9/Qwk37p/aZPO6SFoMwbbBzcQ+RnPVYkIQe2fbLf6Tc9abITxB2WANxULGeHcFR0MvEnLlMtAj3mTwY81y7jfD3McN1OObCd619mmXQhECj+XC+oSiAkai0xDl4J2Czp8wF6UR3k/BhX4yYX9ZXAIsD9A3JZiFOI/5JHDSSlcbpGhppz1+ACCzZx+hoF/MOlSnS9ALFy12t6nLa9Q8hIMOqNUosesoEX06EbDePfLPK2g+Z/k25lUrbIhjBtk5ZkgotVhoJr8pDDsUQjISn0z3AOBZb3O7Z9OnJo341BSHBu8VMC+AcoDb6X288G+bAHhU+W57b/PPqfAjWF2F76u7ajQrOBrPX1DkI4jIY0+3m6mOKgKvaC5CzgK1VyOLmVQMqYLTsaqgm2RM5hLMgeZ6FXdL5FsGSKyWxUpoM3zHWiJry9hDudQ1VOf9aw9s5gAyE1nuRsh2I/ug9VuEGuL4kZVPSsUJki+iwUzZv7XzqStbtkt30+6Bm1xfcyQQuOBKYGt19ajTriG09kDVw6LhvB7EWmcX9qqr3OODFV6eFI+ozSL2phU=
    - secure: EIMlvCNuHnicpahr8LWVVMr5NE+OrkOZYYM9TTgNlNzoiBgzGGv0K/Zc5QjQuoYHqavD6tqSNmhBJ4XaIt7c9ymxYKMBiRFZsNW5z6mfyWukDpRUZONq9TXrBoeaSWpwiaAr2fAlTacU7Y2uH0Y9VMBriwLxbAToNYJFDEvHyiJVIZeDfRvMQVuoVBQIRveYB/nVHyl8VLNEIm8yIeP2j6L0iSenEiT+5ApQt3z+R52ujLR742p0+TFvBCmGWLRb2JvbgU29nSESKbdjxt9AllJEmjgQEjwiWL2nI6T0ETp7vDXk8W/un5V2AIxvkCZJ3EcCa88ftU0tU9+a+pOW+i8w0Hl2KBpEYAm7Ut6Rml2hnKiVXW4jFzruoyKkpW10zuCcev+0fj/oNzpYCNafgrX1ZBK1A/+tR3Ld8hK4oE4EzW/EMIICPmlumVJfZx6bzCe97v6vik/8nxZ7fj2uVSqd9lfq86tvnZ3fQ4cjeY3hNx8OtW6xli8YFfHyKtmYxJYI8EUmDeCGGOqeKsn3JDJWsFYd4678+gvndGgfZH2mtxukBDJ1wODwjPf1ubhciOmH+bN3irOytiSz1U7fqDL4rmgQSono34hH0n2oRE8v68NTcp61VAZB0B6XUMwRVuFVdLTB01WMHQBOhlzjuzPh6cfqb1b0jKiL6hb6dH8=

before_install:
  - openssl aes-256-cbc -K $encrypted_fd443337f3b8_key -iv $encrypted_fd443337f3b8_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d

after_success:
  - .travis/deploy.sh
